### ISSUE TITLE
Is crashing when ain't the main viewController

### ISSUE THREAD

**Issue by allanscofield** [demon1105/PinterestSwift#11]
When you have a screen before the main pinterest screen, the back is giving crash.

**Comment by zzz6519003** [comment]
求倒数第二张图的妹子高清图~。~

**Comment by demon1105** [comment]
@zzz6519003 
https://www.google.com/search?tbs=sbi:AMhZZis78YvmGJhKOGs8g20vSmsNw5GYKEmHkQDA-cHvvkhvf6c-xAs4P2l0uCEVUeVXbN4WrcakVLbVDyf1ov1mHO404Kn0HURuGNPKKHUL3ZhWttKV8GtiBpL2qSCCKmxQFSuFwUxENWBVE3QUfdMm0mJhWWQ5ghEBBa0gQEytlKXuz-oQNePGW8jZnYLxEt-HdLIff7MIhFnQWylZ4ULycMLK_1XO2aZPP8A2_1PxNd7EHzwj8YM_1yXTwq4wh7bsxWWcgUrW-GLvzQiK6_10d-WjlR-qSQBng-vTYZ_1SFPuag905acDfRRq4UoWEd9lWg8rfncINCSxul-Ia6ac9UWqTXAytYSkEAc-ME0krBJGPc_19ypnS_1sUd-hZhPHYeYNXyRP0PAokGK33BEef23Wx3so3S4D8larLjQ4dUmAMKEKctSNWudCPcxjbpmSfaSr4Ed-b2f3PQmL-ovUGF2OIAfNnb2SRKHtFdWP3gdgtsn9HggyR6U-gNvoRpHz3HK4BreCDU2LDKNUmFf93j-W5yQYZmBZn5AyReNHXvVVz3j7zKuw6p3FxEaXdKjKVYORLVlxqSMH-1sqvMJKUSwkk_1xO6oz_1MVBAYOP3XTHAAvCNSmaq3abSZWz4piY8RRvmIzPDk6c2Q3Hs8gHB2sw2A5ZhY9Kbb2ZI-o2mxTj6lA6tS6VgVvOL73P4XfbMADvRNgeE_1lohMGybO5h_1_1iA2NiOMGoGwpkCQhes183JTPdJbR8tk0nB96iODFJY7hMQ7GEqvZbE0LWg8pQh-Uh6MPg4nd02UaQzj83TVVP9N9TCttSzsMpXc_1enRKrPx88l-HpmrZVChxz202lzGX-3CjNIdTVlRXzOxVRv9gC6KosPLxEBNsdFLqfmaWlzLB1kC7cH55AY6a7CAMpSxg6bN8rBNTLovcZ7RvUPS1qlnR0Qxj4pbf52wDeND7qbZ-jVoJey1NL9uiGAKFJhcDcTZakEu2uKXHNvAf-jLSgM1ZYqtHezaDN-sD8wyheXj7gHr1CvuJdRRDmXyFcwB7WGsVRSZ04-d6wRTSj2Bae_15SOP7W6sy2DmON3u3bsHFzEkt4qfBmtr8rbxcqMsquQPWfr6ekAHJzBUBiZhVeMwhM1iEZOml5MUuepwLSGHUA5tzmnAAivU7Ks_1c5SPCjWW_1XAW46tRt8dqWcOKlVIBjneYUsuZFQfPidPIBox374Q0i1R7G-lXiSJprY2X6RSULQl-_1IaOvxB3XJCeFIaRV69gyOG1ZONc-MpNS5zkrtS4IL2k2r8do8YOevHwK6fiHmJMJmYIv92awPsfPkcplinD9Z0RG_1EHFABEnO2CP1SbaRdHQUNe83eMeshVmExudBEGITqrDRNlnz99_1bHybuqCyzUSWqkdF_1Qlgk1AgfXPuBjehcMFbhqJfOsvaXp_13ooyl7lKzSnNS9N_1mSFNlv3wAGv-tWM2T7tvvKChrtZKHIeACH5u3a9qhV6CNybNTCv6z0svUqPmAQvHtp8pcCWJIQ31DTzajay3hNcAVViwwkJmLsjmxPp1

good luck...
