### ISSUE TITLE
Swipe from left gesture

### ISSUE THREAD

**Issue by cannyboy** [demon1105/PinterestSwift#13]
As well as the custom shrink effect, Pinterest lets you swipe from left to go back. Is it possible to include this in PinterestSwift? Alternatively, could the custom transition be animated as the user swipes from the left?

![swipe](https://cloud.githubusercontent.com/assets/1590436/7988583/1b1d4000-0adc-11e5-9e59-22f37af3638c.png)

**Comment by demon1105** [comment]
To pop view controller by interactive gesture, we can override the other functions when implement UIViewControllerTransitioningDelegate protocol, looks like `interactionControllerForPresentation ` or something else, it seems more complex interactive transition will be available, you can try it whatever you like. :smiley:

**Comment by cannyboy** [comment]
Is there any code you could share for this?

**Comment by demon1105** [comment]
@cannyboy 
[here](https://github.com/ColinEberhardt/VCTransitionsLibrary) is a repo to demonstrate a lot of transitions, interacted transition is included in. Good luck.
